// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Input *inputIn;
  Fl_Button *btnClear;
  Fl_Button *btnUpdate;
  Fl_Button *btnDelete;
  Fl_Button *btnInsert;
  Fl_Browser *browser;
  Fl_Input *inputOut;
  Fl_Button *btnImport;
  Fl_Button *btnImport;
  Fl_Input *inputTitle;
  Fl_Input *inputId;
  Fl_Input *inputLabel;
};
#endif
