// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(435, 520, "Random Demo");
    w->box(FL_EMBOSSED_BOX);
    w->user_data((void*)(this));
    { inputValue = new Fl_Int_Input(155, 282, 140, 22, "Participantes");
      inputValue->type(2);
    } // Fl_Int_Input* inputValue
    { boxResult = new Fl_Box(87, 338, 265, 67);
      boxResult->box(FL_DOWN_BOX);
      boxResult->labelsize(28);
    } // Fl_Box* boxResult
    { btnRst = new Fl_Button(305, 281, 75, 24, "Reset");
    } // Fl_Button* btnRst
    { btnSort = new Fl_Button(87, 414, 265, 46, "Sortear");
    } // Fl_Button* btnSort
    { boxNum = new Fl_Box(165, 312, 125, 18);
    } // Fl_Box* boxNum
    { boxImg = new Fl_Box(25, 25, 380, 207);
    } // Fl_Box* boxImg
    w->end();
  } // Fl_Double_Window* w
}
