// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <vector>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Int_Input *inputValue;
  Fl_Box *boxResult;
  Fl_Button *btnRst;
  Fl_Button *btnSort;
  Fl_Box *boxNum;
  Fl_Box *boxImg;
  int index=0; //indíce do vetor
  std::vector<int> numSort; //vetor com os números para sorteio
};  
#endif
